apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
        - name: challenge
          image: challenge_ashpect:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
